In [27]:
%run ../../data/api_keys.ipynb
%run ../modulos.ipynb

In [30]:
# Muestra de request
headers = {"Authorization": f"Bearer {personal_access_token}"}

In [7]:
client=pymongo.MongoClient('mongodb://localhost:27017/')
database=client['promisearch'] # database
collecion_repos=database['repositorios'] # colección

## Obtencion de repositorios a traves de busquedas

In [143]:
def get_pages_repos(min_estrellas, max_estrellas, num_pagina=1):
    """
    Ejemplo:
    f'https://api.github.com/search/repositories?per_page=100&page=5&q=stars%3A1..1000&s=forks'
    """
    
    #return f"https://github.com/search?l=&p={num_pagina}&q=stars%3A{min_estrellas}..{max_estrellas}&ref=advsearch&type=Repositories"
    #return f'https://api.github.com/search/repositories?q=stars%3A{min_estrellas}..{max_estrellas}&s=forks'
    return f'https://api.github.com/search/repositories?per_page=100&page={num_pagina}&q=stars%3A{min_estrellas}..{max_estrellas}&s=forks'

## Obtención de repositorios

https://docs.github.com/en/rest/search#search-repositories

In [33]:
min_estrellas_lista = [10 + i for i in range(10)] + [20 + 2 * i for i in range(5)] + [31, 41, 71, 161]
max_estrellas_lista = [10 + i for i in range(10)] + [22 + 2 * i for i in range(5)] + [40, 70, 160, 350000]

In [141]:
# Eliminar basse
collecion_repos.drop()

In [142]:
list(collecion_repos.find())

[]

In [127]:
get_pages_repos(1,100, 10)

'https://api.github.com/search/repositories?q=stars%3A1..100&s=forks&page=page10'

In [128]:
requests.get('https://api.github.com/search/repositories?q=stars%3A1..100&s=forks&page=page10' ,headers=headers)

<Response [200]>

In [144]:
personal_access_token = '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'
headers = {"Authorization": f"Bearer {personal_access_token}","Accept": "application/vnd.github.v3.star+json","content-type": "application/json"}

stars_list = []
resultados = []
repos_final = {}
rangos_estrellas = list(zip(min_estrellas_lista, max_estrellas_lista))
min_estrellas = 0
max_estrellas = 1000

lista_tmp = []
rand_pags=1
for _ in range(10):
    repos_bins = []

    i=0
    while i <1:
        # página aleatoria
        #num_pagina = rand_pags

        # Construyo la URL
        url_objetivo = get_pages_repos(min_estrellas, max_estrellas, rand_pags)
        #print(rand_pags)
        #print(url_objetivo)
        # Aqui hago la peticion a github
        # search_github = requests.get(url_objetivo)
        search_github = requests.get(url_objetivo ,headers=headers)
        #print(search_github)
        search_github_json = search_github.json()

        try:
            lista_repos = search_github_json['items'] # 30 repos
            lista_random = random.sample(lista_repos, 99)                        
            repos_bins.extend(lista_random)
            lista_tmp.extend(lista_random)
            
            print(f'Todo bien {_+1}')
            resultados.append(search_github_json['total_count'])
            stars_list.append([min_estrellas, max_estrellas])
        except:  
            print(search_github_json)
            time.sleep(61)
            i-=1
        i+=1
    rand_pags += 1
    
    # print(repos_bins)
    #repos_final[f'{min_estrellas}-{max_estrellas}'] = repos_bins
    collecion_repos.insert_one({f'{_}':repos_bins})

Todo bien 1
Todo bien 2
Todo bien 3
Todo bien 4
Todo bien 5
Todo bien 6
Todo bien 7
Todo bien 8
Todo bien 9
Todo bien 10


In [156]:
len(lista_tmp)

990

In [154]:
a = set()

for i in lista_tmp:
    longitud_l1 = len(a)
    a.add(i['full_name'])
    longitud_l2 = len(a)
    if longitud_l1 == longitud_l2:
        print(i['full_name'])

scribu/wp-posts-to-posts
asystat/Final-Android-Resizer
oortcloud/meteorite
higgsjs/Higgs
taion/react-router-scroll
pfefferle/openwebicons
DavyJonesLocker/ember-validations
Zepo/GYDataCenter
bauhouse/fluid960gs
ajoslin/angular-mobile-nav
daimajia/EverMemo
websymphony/almost-flat-ui
rev087/ng-inspector
yannickl/AwaitKit
raycmorgan/Mu
Otbivnoe/CodableAlamofire
LinkedInAttic/LIExposeController
cloudfoundry-attic/lattice-release
inikulin/publish-please
Rano1/Interactive-animation
leerduo/InterviewQuestion
mwaylabs/The-M-Project
binaryage/dirac
powy1993/fullpage
Orbiter/OpenWebIndex
martijnwalraven/meteor-ios
NUBIC/surveyor
wikichen/sketch-android-kit
weightshift/The-Personal-Page
makaroni4/sandi_meter
raganwald/javascript-allonge
openfaas/openfaas-cloud
Vaberer/Font-Awesome-Swift
Cleveroad/LoopBar
mogutt/TTAndroidClient
celrenheit/lion


In [155]:
len(a)

954

In [140]:
for i in a:
   i == 'https://api.github.com/repos/alexmic/filtrr':
   

{'https://api.github.com/repos/Accenture/adop-docker-compose',
 'https://api.github.com/repos/Ahmkel/Keras-Project-Template',
 'https://api.github.com/repos/AlvaroFranco/AFSoundManager',
 'https://api.github.com/repos/Aspsine/IRecyclerView',
 'https://api.github.com/repos/AzimoLabs/AndroidKeyboardWatcher',
 'https://api.github.com/repos/C4Labs/C4iOS',
 'https://api.github.com/repos/CharlinFeng/CoreLock',
 'https://api.github.com/repos/ColinEberhardt/LinqToObjectiveC',
 'https://api.github.com/repos/CouscousPHP/Couscous',
 'https://api.github.com/repos/DataTables/VisualEvent',
 'https://api.github.com/repos/Datawalke/Coordino',
 'https://api.github.com/repos/DavyJonesLocker/ember-validations',
 'https://api.github.com/repos/Dobiasd/programming-language-subreddits-and-their-choice-of-words',
 'https://api.github.com/repos/ErikvdVen/php-gif',
 'https://api.github.com/repos/FiloSottile/gvt',
 'https://api.github.com/repos/ForbesLindesay/connect-roles',
 'https://api.github.com/repos/Henrik

In [136]:
len(a)

296

In [106]:
repos_bins

30

In [100]:
tmp = list(collecion_repos.find())

In [71]:
len(tmp[18]['0-1000'])

30

In [ ]:
%title Prueba
url_objetivo = get_pages_repos(161, 350000, 1)
search_github = requests.get(url_objetivo ,headers=headers)
search_github_json = search_github.json()

search_github_json['items'][0]

{'id': 28457823,
 'node_id': 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
 'name': 'freeCodeCamp',
 'full_name': 'freeCodeCamp/freeCodeCamp',
 'private': False,
 'owner': {'login': 'freeCodeCamp',
  'id': 9892522,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/9892522?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/freeCodeCamp',
  'html_url': 'https://github.com/freeCodeCamp',
  'followers_url': 'https://api.github.com/users/freeCodeCamp/followers',
  'following_url': 'https://api.github.com/users/freeCodeCamp/following{/other_user}',
  'gists_url': 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/freeCodeCamp/subscriptions',
  'organizations_url': 'https://api.github.com/users/freeCodeCamp/orgs',
  'repos_url': 'https://api.github.com/users/freeCodeCamp/repos',
  'event

### Definición del muestreo

El número de bins es 19.

El número de páginas que queremos por bins es 10.

El número de repos que queremos por página es 10.

Nueva división:

* 10 a 20: uno por uno.
* 20 a 30: dos por dos.
* 30 a 40: un bin.
* 40 a 70: un bin.
* 70 a 160: un bin.
* 160 a $\infty$: un bin.

In [ ]:
list(zip(min_estrellas_lista, max_estrellas_lista))[5]

(15, 15)

In [34]:
stars_list = []
resultados = []
repos_final = {}
rangos_estrellas = list(zip(min_estrellas_lista, max_estrellas_lista))

for min_estrellas, max_estrellas in rangos_estrellas:
    repos_bins = []
    rand_pags=random.sample(list(range(100)),10)
    i=0
    while i <10:
        # página aleatoria
        num_pagina = rand_pags[i]

        # Construyo la URL
        url_objetivo = get_pages_repos(min_estrellas, max_estrellas, num_pagina)
        
        # Aqui hago la peticion a github
        # search_github = requests.get(url_objetivo)
        search_github = requests.get(url_objetivo ,headers=headers)
        #print(search_github)
        search_github_json = search_github.json()

        try:
            lista_repos = search_github_json['items']
            lista_random = random.sample(lista_repos, 10)
            repos_bins.extend(lista_random)
            print(f'Todo bien {_+1}')
            resultados.append(search_github_json['total_count'])
            stars_list.append([min_estrellas, max_estrellas])
        except:  
            print(search_github_json)
            time.sleep(61)
            i-=1
        i+=1

    # print(repos_bins)
    repos_final[f'{min_estrellas}-{max_estrellas}'] = repos_bins
    collecion_repos.insert_one({f'{min_estrellas}-{max_estrellas}':repos_bins})

{'documentation_url': 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits', 'message': 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'}


KeyboardInterrupt: 

In [ ]:
repos_final.keys()

dict_keys(['10-10', '11-11'])

# Análisis estadístico

In [ ]:
bins = np.linspace(0, sum(resultados), 10)
bins

array([      0.        ,  177980.77777778,  355961.55555556,
        533942.33333333,  711923.11111111,  889903.88888889,
       1067884.66666667, 1245865.44444444, 1423846.22222222,
       1601827.        ])

In [ ]:
deciles = np.searchsorted(bins, x)
print(np.argmin(np.abs(deciles - 9)))
deciles

15


array([4, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,

In [ ]:
min_estrellas = [10 + i for i in range(10)] + [20 + 2 * i for i in range(5)] + [31, 41, 71, 161]
max_estrellas = [10 + i for i in range(10)] + [22 + 2 * i for i in range(5)] + [40, 70, 160, 500000]

print(min_estrellas)
print(max_estrellas)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 31, 41, 71, 161]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 24, 26, 28, 30, 40, 70, 160, 500000]


In [ ]:
x = np.cumsum(resultados)
x

array([ 640685,  892812, 1032287, 1122649, 1186823, 1234692, 1272325,
       1302813, 1327300, 1348045, 1366052, 1381680, 1395399, 1407434,
       1418233, 1427843, 1436742, 1444785, 1451892, 1458487, 1464391,
       1469865, 1475022, 1479890, 1484511, 1488757, 1492896, 1496593,
       1500086, 1503324, 1506280, 1509070, 1511663, 1514187, 1516661,
       1518978, 1521173, 1523269, 1525238, 1527149, 1529001, 1530715,
       1532348, 1533918, 1535466, 1536998, 1538351, 1539683, 1540992,
       1542281, 1543535, 1544732, 1545911, 1547042, 1548109, 1549172,
       1550204, 1551212, 1552113, 1553044, 1553916, 1554817, 1555662,
       1556453, 1557257, 1557983, 1558684, 1559352, 1560028, 1560727,
       1561442, 1562109, 1562728, 1563297, 1563926, 1564530, 1565090,
       1565694, 1566261, 1566806, 1567277, 1567797, 1568292, 1568761,
       1569228, 1569714, 1570156, 1570590, 1571028, 1571427, 1571806,
       1572198, 1572570, 1572928, 1573267, 1573598, 1573913, 1574219,
       1574550, 1574

In [ ]:
intervalos_str = [str(intervalo) for intervalo in stars_list]
fig = px.bar(x=intervalos_str[0:], y=resultados[0:])
fig.update_layout(template='plotly_dark')
fig.show()

In [ ]:
serie_resultados = pd.

In [ ]:
intervalos_str = [str(intervalo) for intervalo in stars_list]
fig = px.bar(x=intervalos_str[1:], y=resultados[1:])
fig.update_layout(template='plotly_dark')
fig.show()

Analizar el muestreo

10..20
100..200
1000..2000
1000..20000
10000..20000 # 5 cero

{'total_count': 640606,
 'incomplete_results': False,
 'items': [{'id': 236652,
   'node_id': 'MDEwOlJlcG9zaXRvcnkyMzY2NTI=',
   'name': 'objectpool',
   'full_name': 'ahoward/objectpool',
   'private': False,
   'owner': {'login': 'ahoward',
    'id': 6094,
    'node_id': 'MDQ6VXNlcjYwOTQ=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/6094?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/ahoward',
    'html_url': 'https://github.com/ahoward',
    'followers_url': 'https://api.github.com/users/ahoward/followers',
    'following_url': 'https://api.github.com/users/ahoward/following{/other_user}',
    'gists_url': 'https://api.github.com/users/ahoward/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/ahoward/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/ahoward/subscriptions',
    'organizations_url': 'https://api.github.com/users/ahoward/orgs',
    'repos_url': 'https://api.github.com/users/ahoward/re

30

In [ ]:
dict_body['items'][0]

{'id': 56186352,
 'node_id': 'MDEwOlJlcG9zaXRvcnk1NjE4NjM1Mg==',
 'name': 'TweetSploit',
 'full_name': 'davidsilveiro/TweetSploit',
 'private': False,
 'owner': {'login': 'davidsilveiro',
  'id': 17771839,
  'node_id': 'MDQ6VXNlcjE3NzcxODM5',
  'avatar_url': 'https://avatars.githubusercontent.com/u/17771839?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/davidsilveiro',
  'html_url': 'https://github.com/davidsilveiro',
  'followers_url': 'https://api.github.com/users/davidsilveiro/followers',
  'following_url': 'https://api.github.com/users/davidsilveiro/following{/other_user}',
  'gists_url': 'https://api.github.com/users/davidsilveiro/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/davidsilveiro/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/davidsilveiro/subscriptions',
  'organizations_url': 'https://api.github.com/users/davidsilveiro/orgs',
  'repos_url': 'https://api.github.com/users/davidsilveiro/repos',
  'events


## Muestreo (Una vez que defina)

In [ ]:
import random
random.sample(links_repos, 5)
links_repos

['/iina/iina',
 '/unknwon/the-way-to-go_ZH_CN',
 '/streamich/react-use',
 '/FFmpeg/FFmpeg',
 '/jgraph/drawio-desktop']

['/go-gitea/gitea',
 '/iina/iina',
 '/brillout/awesome-react-components',
 '/laurent22/joplin',
 '/FFmpeg/FFmpeg',
 '/jgraph/drawio-desktop',
 '/unknwon/the-way-to-go_ZH_CN',
 '/zxing/zxing',
 '/streamich/react-use',
 '/excalidraw/excalidraw']

In [ ]:
bins = np.linspace(0, sum(resultados), 10)
bins

array([      0.        ,  177980.77777778,  355961.55555556,
        533942.33333333,  711923.11111111,  889903.88888889,
       1067884.66666667, 1245865.44444444, 1423846.22222222,
       1601827.        ])

In [ ]:
list(bins)

[0.0,
 177980.77777777778,
 355961.55555555556,
 533942.3333333334,
 711923.1111111111,
 889903.8888888889,
 1067884.6666666667,
 1245865.4444444445,
 1423846.2222222222,
 1601827.0]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=152a8359-c113-4e0b-abe1-792bdde45c2e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>